# Generated by Django 5.0.6 on 2024-06-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='getappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=50)),
                ('email', models.EmailField(default=0, max_length=50)),
                ('address', models.CharField(default=0, max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('option_gender', models.CharField(default=0, max_length=20)),
                ('option_doctor', models.CharField(default=0, max_length=50)),
                ('date', models.CharField(default=0, max_length=50)),
                ('time', models.CharField(default=0, max_length=50)),
                ('reason', models.CharField(default=0, max_length=200)),
            ],
            options={
                'db_table': 'getappointment',
            },
        ),
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
                ('repwd', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('chose1', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userdata',
            },
        ),
    ]
