# Generated by Django 5.0.6 on 2024-06-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dproject1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='getappointment',
            new_name='appointment',
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
    ]
