# Generated by Django 5.0.6 on 2024-06-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dproject1', '0003_alter_appointment_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
                ('repwd', models.CharField(max_length=50)),
            ],
        ),
    ]
