# Generated by Django 5.0.6 on 2024-06-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dproject1', '0004_admin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
    ]
