# Generated by Django 5.0.6 on 2024-06-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dproject1', '0005_alter_admin_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Priyanka', models.CharField(max_length=50)),
                ('Prabhat', models.CharField(max_length=50)),
                ('Nikhil', models.CharField(max_length=50)),
                ('Prit', models.CharField(max_length=50)),
                ('Mozakkir', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
    ]
