# Generated by Django 5.0.6 on 2024-06-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dproject1', '0006_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Mozakkir_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Nikhil_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Prabhat_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Prit_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Priyanka_slot',
            field=models.IntegerField(default=0),
        ),
    ]
