# Generated by Django 5.0.6 on 2024-06-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dproject1', '0007_doctor_mozakkir_slot_doctor_nikhil_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='fee',
            field=models.IntegerField(default=0),
        ),
    ]
