# Generated by Django 5.0.6 on 2024-06-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dproject1', '0009_alter_appointment_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Mozakkir_slot',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Nikhil_slot',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Prabhat_slot',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Prit_slot',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Priyanka_slot',
        ),
    ]
