# Generated by Django 5.0.6 on 2024-06-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dproject1', '0011_appointment_doctor_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_pwd',
            field=models.CharField(default=123, max_length=50),
        ),
    ]
